/*
import java.util.Scanner;

public class stringArrayIssue {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter array Size : ");
        int size = sc.nextInt();
        String names[] = new String[size];
        for(int i=0;i<names.length;i++){
            System.out.print("Enter Name: ");
            names[i] = sc.nextLine();
        }

        for(int i=0;i<names.length;i++){
            System.out.println("Names : "+names[i]);
        }
        sc.close(); // Close the Scanner object to release resources
    }
}

Output => Enter array Size : 3
          Enter Name: Enter Name: Prince Mishra
          Enter Name: Aakash Gupta
          Names :                   // Empty string being assigned to names[0], due to leftover newline (\n) in input buffer
          Names : Prince Mishra
          Names : Aakash Gupta
*/

import java.util.Scanner;

public class stringArrayIssue {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter array Size : ");
        int size = sc.nextInt();
        /*
        Issue: When sc.nextInt() reads the integer input, it leaves the newline character
        (generated by pressing Enter) in the input buffer. The subsequent sc.nextLine()
        in the loop then immediately reads this leftover newline, resulting in an empty
        string being assigned to the first element of the 'names' array and appearing
        as if the first name input was skipped.
        */
        sc.nextLine(); // Solution: Consume the leftover newline character from sc.nextInt()

        String names[] = new String[size];
        for(int i=0;i<names.length;i++){
            System.out.print("Enter Name: ");
            names[i] = sc.nextLine();
        }

        for(int i=0;i<names.length;i++){
            System.out.println("Names : "+names[i]);
        }
        sc.close(); // Close the Scanner object to release resources
    }
}

/*
Output => Enter array Size : 3
          Enter Name: Prince Mishra
          Enter Name: Aakash Gupta
          Enter Name: Swapnil Sharma
          Names : Prince Mishra
          Names : Aakash Gupta
          Names : Swapnil Sharma
*/
